// Generated by tools/extract_star_system_tables.py — do not edit by hand.
#pragma once

namespace galaxy {
namespace tables {

extern const int k_age_chance[32];
extern const int k_base_spectral_class_chance[32];
extern const int k_star_chance_multiples[32];
extern const int k_age_spectral_evolution[7][4];
extern const int k_age_luminosity_evolution[7][4];
extern const int k_star_magnitude[7][8];
extern const float k_star_mass[7][8];
extern const float k_star_hz[7][8];
extern const int k_type_table[8][7];
extern const char* const k_namepart[128];
extern const char* const k_name_part_start[160];
extern const char* const k_name_part_end[263];

}  // namespace tables
}  // namespace galaxy