"""Parse KnownSpace.cs knownSystems array and emit known_space_catalog.cpp (same math as C# static ctor)."""
import math
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
KS = ROOT / "GalaxyE-master/GalaxyE-master/GalaxyE/Galaxy/KnownSpace.cs"


def tokenize_cs_object_array(body: str) -> list:
    """Tokenize comma-separated mix of \"strings\" and float literals ending in D."""
    tokens: list = []
    i = 0
    n = len(body)
    while i < n:
        while i < n and body[i] in " \t\n\r,":
            i += 1
        if i >= n:
            break
        if body[i] == '"':
            i += 1
            start = i
            while i < n and body[i] != '"':
                i += 1
            tokens.append(body[start:i])
            i += 1
            continue
        # number ... D
        j = i
        while j < n and body[j] not in ", \t\n\r":
            j += 1
        raw = body[i:j].strip()
        raw = raw.rstrip("dD")
        tokens.append(float(raw))
        i = j
    return tokens


def main() -> None:
    text = KS.read_text(encoding="utf-8")
    m = re.search(r"knownSystems = new object\[\] \{([\s\S]*?)\};", text)
    if not m:
        raise SystemExit("could not find knownSystems array")
    body = m.group(1)
    # Drop full-line // comments (e.g. //pleiades)
    body = "\n".join(
        line for line in body.splitlines() if not re.match(r"^\s*//", line)
    )
    tokens = tokenize_cs_object_array(body)
    if len(tokens) % 6 != 0:
        raise SystemExit(f"expected multiple of 6 tokens, got {len(tokens)}")

    galaxy_width = 100000.0
    number_sectors = 8191.0
    sector_size = galaxy_width / number_sectors
    sol_x = 4111
    sol_y = 6303

    sysnum: dict[str, int] = {}
    rows: list[tuple] = []

    count = len(tokens) // 6
    for idx in range(count):
        name0 = str(tokens[idx * 6 + 0]).strip()
        name1 = str(tokens[idx * 6 + 1]).strip()
        longitude = float(tokens[idx * 6 + 2])
        latitude = float(tokens[idx * 6 + 3])
        type_code = str(tokens[idx * 6 + 4]).strip()
        distance = float(tokens[idx * 6 + 5])

        lon = longitude * (math.pi / 180.0)
        lat = latitude * (math.pi / 180.0)
        distance2 = distance * math.cos(lat)
        a = distance2 * math.cos(lon)
        b = distance2 * math.sin(lon)
        a, b = -a, -b
        b += (sol_x * sector_size) + sector_size / 2.0
        a += (sol_y * sector_size) + sector_size / 2.0
        coordx = int(b / sector_size)
        coordy = int(a / sector_size)
        sx = int((b % sector_size) * 128.0 / 12.0) - 63
        sy = int((a % sector_size) * 128.0 / 12.0) - 63
        sz = int((lat * (180.0 / math.pi)) * 256.0 / 24.0)

        key = f"{coordx}.{coordy}"
        if key not in sysnum:
            sysnum[key] = 0
        else:
            sysnum[key] += 1
        num_sys = sysnum[key]

        name = name1 if name1 != "" else name0

        rows.append((coordx, coordy, num_sys, type_code, name, sx, sy, sz))

    def esc(s: str) -> str:
        return s.replace("\\", "\\\\").replace('"', '\\"')

    lines: list[str] = []
    lines.append("// Generated by tools/build_known_space_catalog.py — do not edit by hand.")
    lines.append('#include "galaxylib/known_space.hpp"')
    lines.append("")
    lines.append("#include <cstddef>")
    lines.append("")
    lines.append("namespace galaxy {")
    lines.append("namespace known_space {")
    lines.append("")
    lines.append("const CatalogEntry k_catalog[] = {")
    for coordx, coordy, num_sys, type_code, name, sx, sy, sz in rows:
        lines.append(
            f'    {{ {coordx}u, {coordy}u, {num_sys}, "{esc(type_code)}", "{esc(name)}", '
            f"{sx}, {sy}, {sz} }},"
        )
    lines.append("};")
    lines.append("")
    lines.append(
        "const std::size_t k_catalog_size = sizeof(k_catalog) / sizeof(k_catalog[0]);"
    )
    lines.append("")
    lines.append("}  // namespace known_space")
    lines.append("}  // namespace galaxy")
    lines.append("")

    outp = ROOT / "src/known_space_catalog.cpp"
    outp.write_text("\n".join(lines), encoding="utf-8")
    print("Wrote", outp, "entries", len(rows))


if __name__ == "__main__":
    main()
