"""Extract static tables from StarSystem.cs into star_system_tables.cpp (C++ source)."""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CS = ROOT / "GalaxyE-master/GalaxyE-master/GalaxyE/Galaxy/StarSystem.cs"


def main() -> None:
    cs = CS.read_text(encoding="utf-8")

    def extract_int_array(name: str) -> list[int]:
        m = re.search(
            r"(?:static |private static )?int\[\] "
            + re.escape(name)
            + r" = new int\[\] \{([\s\S]*?)\};",
            cs,
        )
        if not m:
            raise SystemExit(f"missing int[] {name}")
        nums = re.findall(r"-?\d+", m.group(1))
        return [int(x) for x in nums]

    def extract_int_grid(name: str) -> list[list[int]]:
        m = re.search(
            r"(?:private static |static )?int\[\]\[\] "
            + re.escape(name)
            + r" = new int\[\]\[\] \{([\s\S]*?)\n\s*\};",
            cs,
        )
        if not m:
            raise SystemExit(f"missing int[][] {name}")
        grid = []
        for block in re.findall(r"new int\[\] \{([^}]*)\}", m.group(1)):
            nums = [int(x) for x in re.findall(r"-?\d+", block)]
            grid.append(nums)
        return grid

    def extract_float_grid(name: str) -> list[list[float]]:
        m = re.search(
            r"(?:private static |static )?float\[\]\[\] "
            + re.escape(name)
            + r" = new float\[\]\[\] \{([\s\S]*?)\n\s*\};",
            cs,
        )
        if not m:
            raise SystemExit(f"missing float[][] {name}")
        grid = []
        for block in re.findall(r"new float\[\] \{([^}]*)\}", m.group(1)):
            nums = []
            for token in re.findall(r"-?\d+\.?\d*[fF]?|\d+[eE][+-]?\d+", block.replace(" ", "")):
                token = token.rstrip("fF")
                nums.append(float(token))
            grid.append(nums)
        return grid

    def extract_string_array(varname: str) -> list[str]:
        m = re.search(
            r"string\[\] "
            + re.escape(varname)
            + r" = new string\[\] \{([\s\S]*?)\n\s*\};",
            cs,
        )
        if not m:
            raise SystemExit(f"missing string[] {varname}")
        return re.findall(r'"((?:[^"\\]|\\.)*)"', m.group(1))

    age_chance = extract_int_array("AgeChance")
    base_spectral = extract_int_array("BaseSpectralClassChance")
    star_chance_multiples = extract_int_array("StarChance_Multiples")
    age_spectral = extract_int_grid("AgeSpectralEvolution")
    age_lum = extract_int_grid("AgeLuminosityEvolution")
    star_mass = extract_float_grid("StarMass")
    star_mag = extract_int_grid("StarMagnitude")
    star_hz = extract_float_grid("StarHz")
    type_table = extract_int_grid("TypeTable")
    namepart = extract_string_array("namepart")
    name_start = extract_string_array("namePartStart_")
    name_end = extract_string_array("namePartEnd_")

    out: list[str] = []
    out.append("// Generated by tools/extract_star_system_tables.py — do not edit by hand.")
    out.append("")
    out.append("namespace galaxy {")
    out.append("namespace tables {")
    out.append("")

    def emit_int_1d(name: str, arr: list[int]) -> None:
        out.append(f"extern const int {name}[{len(arr)}] = {{")
        for i in range(0, len(arr), 8):
            chunk = arr[i : i + 8]
            out.append("    " + ", ".join(str(x) for x in chunk) + ",")
        out.append("};")
        out.append("")

    def emit_int_2d(name: str, grid: list[list[int]]) -> None:
        rows = len(grid)
        cols = len(grid[0]) if grid else 0
        out.append(f"extern const int {name}[{rows}][{cols}] = {{")
        for row in grid:
            out.append("    { " + ", ".join(str(x) for x in row) + " },")
        out.append("};")
        out.append("")

    def fmt_c_float(x: float) -> str:
        s = f"{x:.12g}"
        if "e" in s or "E" in s:
            return s + "f"
        if "." not in s:
            return s + ".0f"
        return s + "f"

    def emit_float_2d(name: str, grid: list[list[float]]) -> None:
        rows = len(grid)
        cols = len(grid[0]) if grid else 0
        out.append(f"extern const float {name}[{rows}][{cols}] = {{")
        for row in grid:
            out.append("    { " + ", ".join(fmt_c_float(x) for x in row) + " },")
        out.append("};")
        out.append("")

    emit_int_1d("k_age_chance", age_chance)
    emit_int_1d("k_base_spectral_class_chance", base_spectral)
    emit_int_1d("k_star_chance_multiples", star_chance_multiples)
    emit_int_2d("k_age_spectral_evolution", age_spectral)
    emit_int_2d("k_age_luminosity_evolution", age_lum)
    emit_int_2d("k_star_magnitude", star_mag)
    emit_float_2d("k_star_mass", star_mass)
    emit_float_2d("k_star_hz", star_hz)
    emit_int_2d("k_type_table", type_table)

    out.append(f"extern const char* const k_namepart[{len(namepart)}] = {{")
    for s in namepart:
        out.append(f'    "{escape_cpp(s)}",')
    out.append("};")
    out.append("")

    out.append(f"extern const char* const k_name_part_start[{len(name_start)}] = {{")
    for s in name_start:
        out.append(f'    "{escape_cpp(s)}",')
    out.append("};")
    out.append("")

    out.append(f"extern const char* const k_name_part_end[{len(name_end)}] = {{")
    for s in name_end:
        out.append(f'    "{escape_cpp(s)}",')
    out.append("};")
    out.append("")

    out.append("}  // namespace tables")
    out.append("}  // namespace galaxy")
    out.append("")

    outp_cpp = ROOT / "src/star_system_tables.cpp"
    outp_cpp.write_text("\n".join(out), encoding="utf-8")

    hdr: list[str] = []
    hdr.append("// Generated by tools/extract_star_system_tables.py — do not edit by hand.")
    hdr.append("#pragma once")
    hdr.append("")
    hdr.append("namespace galaxy {")
    hdr.append("namespace tables {")
    hdr.append("")
    hdr.append("extern const int k_age_chance[32];")
    hdr.append("extern const int k_base_spectral_class_chance[32];")
    hdr.append("extern const int k_star_chance_multiples[32];")
    hdr.append("extern const int k_age_spectral_evolution[7][4];")
    hdr.append("extern const int k_age_luminosity_evolution[7][4];")
    hdr.append("extern const int k_star_magnitude[7][8];")
    hdr.append("extern const float k_star_mass[7][8];")
    hdr.append("extern const float k_star_hz[7][8];")
    hdr.append("extern const int k_type_table[8][7];")
    hdr.append(f"extern const char* const k_namepart[{len(namepart)}];")
    hdr.append(f"extern const char* const k_name_part_start[{len(name_start)}];")
    hdr.append(f"extern const char* const k_name_part_end[{len(name_end)}];")
    hdr.append("")
    hdr.append("}  // namespace tables")
    hdr.append("}  // namespace galaxy")
    outp_h = ROOT / "include/galaxylib/star_system_tables.hpp"
    outp_h.write_text("\n".join(hdr), encoding="utf-8")

    print("Wrote", outp_cpp, "and", outp_h)


def escape_cpp(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


if __name__ == "__main__":
    main()
